name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 */6 * * *' # Runs automatically every 6 hours
  workflow_dispatch:      # Allows you to run it manually from GitHub if needed

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit Instance
        run: curl -s -o /dev/null -w "%{http_code}\n" https://medpulse-app.streamlit.app/
